name: Auto Merge Dependency Updates

on:
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@bdfdeec3b356abc3a11adb942cdbf79228d7b794
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-actors: dependabot-preview[bot], dependabot[bot], tjenkinson
          package-block-list: 'is-plain-object, @tjenkinson/boundary'
